### ISSUE TITLE
dragStart in actionMapping not fired

### ISSUE THREAD

**Issue by joachim-bl** [500tech/angular-tree-component#165]
Hi,

I am using Version 2.8.0

I am trying to implement a conditional "allowDrag" behaviour only for special folders.
adding a mapping to "dragStart" has no effect and is never called:

her my code:

```
options = {
    childrenField: 'items',
    idField: 'id',
    isExpandedField: 'expanded',
    nodeClass: (node:TreeNode)=>{return 'treeItem'},
    allowDrag: true,
    allowDrop: (element, {parent, index}) => {
      return true;
    },
    actionMapping:{
      mouse:{
        dragStart:(tree:TreeModel, node:TreeNode, $event:any, {from, to})=>{
          console.log(event);
          return false;
        },
        drop:(tree:TreeModel, node:TreeNode, $event:any, {from, to})=>{
          console.log(tree);
        }
      }
    }
  }
```

It would be helpful if the "allowDrag" was a function, too, like "allowDrop".

regards
Joachim

**Comment by adamkleingit** [comment]
Sure I can add it.
Feel free to make a pull request on your own if you want this functionality quickly.

**Comment by 1010451** [comment]
i tried that code but does not enter on dragStart

**Comment by joachim-bl** [comment]
i have implemented the allowDrag function, but i am not very experienced with github. If i try to push my new branch to the repository to open a pull request, i get a 403?

**Comment by adamkleingit** [comment]
Hi,
You need to fork the repository, push the code to your own remote, and then make a pull request:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by coolkind** [comment]
I am using version 3.2.3 but still encounter same issue. I hope it can provide me with a workable dragStart actionMapping or allowDrag function callbacks like allowDrop.

**Comment by adamkleingit** [comment]
Hi, added and published in 3.2.4.
All the best
